server {
    listen 80;
    server_name novastudent.kesug.com;

    root /var/www/novastudent-web;
    index index.html;
    client_max_body_size 25m;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
